### ISSUE TITLE
ios模拟器启动闪退

### ISSUE THREAD

**Issue by Myoursky** [kenvies/ONE-ReactNative#1]
你好，我这边通过react-native run-ios启动项目，能够正常打包项目，但是项目点击后直接闪退，也没有什么报错提示。
![image](https://user-images.githubusercontent.com/4679709/29482923-5980b288-84cd-11e7-9f10-7ca59573de60.png)

**Comment by kenvies** [comment]
你用xcode你跑你的ios原生项目，然后用npm start 启动服务，
